#!/usr/bin/env node
/**
 * A sample video for the e2e harnesses, generated by the mpv we already ship.
 *
 * WHY THIS EXISTS. `scripts/e2e-overlay.mjs` is the ONLY check in this repo that
 * asserts the generated settings page actually rendered (`settings.rows < 8`) --
 * that page is where all 38 Wave-1 modules land their descriptors -- and it was
 * excluded from CI. The reason it was excluded is this line:
 *
 *     if (!sample) throw new Error('no sample video under samples/; ...')
 *
 * `samples/` is in `.gitignore` (60 MB of Big Buck Bunny), so a fresh checkout
 * has nothing to play, and a harness that cannot play anything cannot assert
 * that the overlay is alive. §11 of the parity spec already says the repo must
 * stay small and that samples come from a script.
 *
 * So: no download, no new dependency, no checked-in binary. The pinned mpv in
 * `resources/mpv/` has libavformat's encoders, and `av://lavfi:` gives it
 * something to encode. 200 seconds, because `e2e-overlay.mjs` writes an
 * FFMETADATA file with chapters at 0 s, 60 s and 180 s and M25 draws nothing
 * with fewer than two.
 *
 * It never overwrites an existing sample: a developer with the real Big Buck
 * Bunny keeps it.
 *
 * Run: node scripts/make-sample.mjs
 */
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const samples = path.join(repo, 'samples')
const target = path.join(samples, 'bbb.mp4')
const SECONDS = 200

const existing = ['bbb_long.mp4', 'bbb.mp4']
  .map((f) => path.join(samples, f))
  .find((f) => fs.existsSync(f))
if (existing) {
  console.log(`make:sample: ${path.relative(repo, existing)} already exists; leaving it alone`)
  process.exit(0)
}

const mpv = path.join(repo, 'resources', 'mpv', 'mpv.exe')
if (!fs.existsSync(mpv)) {
  console.error(
    `make:sample: no mpv at ${mpv}. Run \`npm run fetch:mpv\` first -- this script encodes ` +
      `with the pinned binary rather than adding an ffmpeg dependency.`
  )
  process.exit(1)
}

fs.mkdirSync(samples, { recursive: true })
execFileSync(
  mpv,
  [
    `av://lavfi:testsrc2=size=320x240:rate=10:duration=${SECONDS}`,
    '--no-config',
    `--audio-file=av://lavfi:sine=frequency=440:duration=${SECONDS}`,
    `--o=${target}`,
    '--of=mp4',
    '--ovc=libx264',
    '--ovcopts=preset=ultrafast,crf=45,g=100',
    '--oac=aac',
    '--oacopts=b=32k',
    '--no-terminal'
  ],
  { stdio: 'inherit' }
)

if (!fs.existsSync(target)) {
  console.error('make:sample: mpv produced no file')
  process.exit(1)
}
const size = fs.statSync(target).size
console.log(`make:sample: samples/bbb.mp4, ${SECONDS}s, ${(size / 1048576).toFixed(1)} MB`)
