import test from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  BANNED_COMMANDS,
  CHAIN_COMMANDS,
  COMMAND_SIDE_EFFECTS,
  CORE_OWNERSHIP,
  OwnerMap
} from './ownership.ts'

/**
 * test:command-ownership — the half of §3.7 that did not exist.
 *
 * WHAT WENT WRONG. §3.7 was built entirely around PROPERTIES. A command was
 * only checked if some module happened to list it in `ownsCommands`, and five of
 * the most consequential ones were listed by nobody: `seek`, `frame-step`,
 * `frame-back-step`, `revert-seek`, `sub-seek`. M24 declared
 * `ownedCommands: []`, so `assertCommand('nav-chapters', 'seek', strict)`
 * returned true — and §3.6's M25 row, which says in English that N51 "seeks
 * through M24's command, it does not own seeking", enforced nothing. That is the
 * identical failure mode as the `sub-reload` bug fixed one round earlier, with
 * the fix mechanism shipped and then not used.
 *
 * Three checks, in increasing order of how much they would have hurt to skip:
 *
 *   1. The side-effect table names only commands the PINNED BINARY has. Names
 *      come from `docs/parity/mpv-commands.json`, generated by
 *      `scripts/dump-mpv-commands.mjs` from `--input-cmdlist`, so a typo or a
 *      command mpv renamed is a failing test rather than a guard that silently
 *      matches nothing.
 *   2. Every command that mutates state has exactly one owner, or is banned.
 *   3. The SPEC's own prose is cross-checked against `modules.json`. Where a row
 *      says a module owns a command, the manifest has to encode it. This is the
 *      check that turns "unenforced prose" into a build failure.
 */

const here = path.dirname(fileURLToPath(import.meta.url))
const repo = path.resolve(here, '..', '..', '..', '..')

interface Row {
  id: string
  path: string
  ownedCommands: string[]
}

const modules: Row[] = JSON.parse(
  fs.readFileSync(path.join(repo, 'docs', 'parity', 'modules.json'), 'utf8')
)
const spec = fs.readFileSync(path.join(repo, 'docs', 'parity', '00-parity-spec.md'), 'utf8')
const dump: { version: string; commands: string[] } = JSON.parse(
  fs.readFileSync(path.join(repo, 'docs', 'parity', 'mpv-commands.json'), 'utf8')
)
const MPV_COMMANDS = new Set(dump.commands)

/** Core plus every manifest row, folded exactly the way the registry folds it. */
function ownerMap(): OwnerMap {
  return new OwnerMap([
    ...CORE_OWNERSHIP.map((c) => ({ id: c.id, ownsCommands: c.ownsCommands ?? [] })),
    ...modules
      .filter((m) => !m.id.startsWith('core'))
      .map((m) => ({ id: m.id, ownsCommands: m.ownedCommands }))
  ])
}

/**
 * mpv accepts these over JSON IPC but does not list them in `--input-cmdlist`:
 * they are the legacy aliases of `set` / `get`. Measured on the pinned binary —
 * `['set_property_string','aid','1']` returns `success` and writes — which is
 * exactly why `PROPERTY_WRITING_COMMANDS` carries them.
 */
const UNLISTED_ALIASES = new Set(['set-property', 'set-property-string', 'get-property'])

test('the captured command list matches the pinned binary', () => {
  const exe = path.join(repo, 'resources', 'mpv', 'mpv.exe')
  if (!fs.existsSync(exe)) return // CI runs with --ignore-scripts and has no binary
  const live = execFileSync(exe, ['--input-cmdlist'], { encoding: 'utf8', maxBuffer: 4 << 20 })
    .split(/\r?\n/)
    .map((l) => l.trim().split(/\s+/)[0])
    .filter((n) => n && /^[a-z][a-z0-9_-]*$/.test(n))
    .sort()
  assert.deepEqual(
    live,
    dump.commands,
    'docs/parity/mpv-commands.json is stale; re-run scripts/dump-mpv-commands.mjs'
  )
})

test('every command in the side-effect table exists in mpv', () => {
  for (const name of Object.keys(COMMAND_SIDE_EFFECTS)) {
    assert.ok(
      MPV_COMMANDS.has(name),
      `COMMAND_SIDE_EFFECTS names '${name}', which is not in ${dump.version}'s --input-cmdlist. ` +
        `A guard on a command that does not exist guards nothing.`
    )
  }
  for (const name of [...BANNED_COMMANDS, ...CHAIN_COMMANDS]) {
    assert.ok(MPV_COMMANDS.has(name), `'${name}' is banned/chain-reserved but mpv has no such command`)
  }
})

test('every command anyone claims to own exists in mpv', () => {
  const claims: Array<[string, string]> = []
  for (const c of CORE_OWNERSHIP) for (const n of c.ownsCommands ?? []) claims.push([c.id, n])
  for (const m of modules) for (const n of m.ownedCommands) claims.push([m.id, n])

  for (const [owner, claim] of claims) {
    if (UNLISTED_ALIASES.has(claim)) continue
    const matches = claim.endsWith('*')
      ? [...MPV_COMMANDS].some((c) => c.startsWith(claim.slice(0, -1)))
      : MPV_COMMANDS.has(claim)
    assert.ok(
      matches,
      `${owner} claims mpv command '${claim}', which ${dump.version} does not have. ` +
        `Fix the name or drop the claim — a stale claim reserves nothing and blocks nobody.`
    )
  }
})

/**
 * THE ONE THAT WOULD HAVE CAUGHT IT. `seek` had no owner, so anybody could seek.
 */
test('every state-mutating command has exactly one owner', () => {
  const map = ownerMap()
  const unowned: string[] = []
  for (const name of Object.keys(COMMAND_SIDE_EFFECTS)) {
    if (BANNED_COMMANDS.has(name)) continue
    if (!map.commandOwnerOf(name)) unowned.push(name)
  }
  assert.deepEqual(
    unowned,
    [],
    `these commands write an mpv property and belong to nobody, so assertCommand() lets ` +
      `every module issue them:\n  ${unowned.join('\n  ')}\n` +
      `Give each one an owner in docs/parity/modules.json (and in that module's ownsCommands).`
  )
})

test('a command owner also owns, or can mediate, the properties that command writes', () => {
  // Not a hard failure when the writer is core -- `frame-step` writing `pause`
  // is legitimate and M24 mediates through core.play/core.pause -- but a module
  // owning a command whose side effect belongs to a THIRD module is a design
  // gap worth naming out loud.
  const commands = ownerMap()
  const properties = new OwnerMap([
    ...CORE_OWNERSHIP,
    ...modules
      .filter((m) => !m.id.startsWith('core'))
      .map((m) => ({
        id: m.id,
        ownsProperties: (m as unknown as { ownedProperties: string[] }).ownedProperties
      }))
  ])
  const row = (id: string): Row | undefined => modules.find((m) => m.id === id)
  /** A declared dependency the holder actually answers is a design, not a gap. */
  const mediated = (owner: string, holder: string, property: string): boolean => {
    const declared = (row(owner) as unknown as { requestsProperties?: string[] })?.requestsProperties
    if (!declared?.includes(property)) return false
    const h = row(holder) as unknown as {
      arbitrates?: string[]
      mediates?: Record<string, string[]>
    }
    if (h?.arbitrates?.includes(property)) return true
    return Object.values(h?.mediates ?? {}).some((covered) => covered.includes(property))
  }

  const notes: string[] = []
  for (const [command, props] of Object.entries(COMMAND_SIDE_EFFECTS)) {
    const owner = commands.commandOwnerOf(command)
    if (!owner) continue
    for (const p of props) {
      const holder = properties.ownerOf(p)
      if (holder === null || holder === owner || holder.startsWith('core')) continue
      if (mediated(owner, holder, p)) continue
      notes.push(`'${command}' (${owner}) writes '${p}' (${holder})`)
    }
  }
  assert.deepEqual(
    notes,
    [],
    `a module owns a command whose side effect lands in a THIRD module's property:\n  ` +
      notes.join('\n  ')
  )
})

// ---------------------------------------------------------------------------
// The spec's prose, cross-checked against the manifest.
// ---------------------------------------------------------------------------

const owns = (moduleId: string, command: string): boolean =>
  modules
    .find((m) => m.id === moduleId)
    ?.ownedCommands.some((c) => (c.endsWith('*') ? command.startsWith(c.slice(0, -1)) : c === command)) ===
  true

/** `**M17 `subs-tracks`**`, `**M20 subs-sync**`, `**M11**` — all three forms. */
function moduleIdsIn(text: string): string[] {
  return [...text.matchAll(/\bM(\d{2})\b/g)].map((m) => `M${m[1]}`)
}

test('every command the spec says a module owns is encoded in modules.json', () => {
  const missing: string[] = []

  for (const line of spec.split(/\r?\n/)) {
    if (!line.startsWith('|')) continue
    const cells = line.split('|').map((c) => c.trim())

    // Form 1 — §1.5 and §3.7's resolution tables: the FIRST cell names the
    // contested thing, a later cell names the winning module in bold.
    //   | `sub-seek` / `sub-step` | navigation, subtitles | **M20 subs-sync** | ... |
    //   | **`sub-reload`** | three, plus a self-contradiction | **M17 `subs-tracks`** | ... |
    const subject = cells[1] ?? ''
    const commandsInSubject = [...subject.matchAll(/`([a-z][a-z0-9-]*)`/g)]
      .map((m) => m[1] as string)
      .filter((c) => MPV_COMMANDS.has(c))
    if (commandsInSubject.length > 0) {
      const winner = cells.slice(2).find((c) => /^\*\*/.test(c) && /\bM\d{2}\b/.test(c))
      const ids = winner ? moduleIdsIn(winner) : []
      if (ids.length === 1) {
        for (const command of commandsInSubject) {
          if (!owns(ids[0] as string, command)) {
            missing.push(`the spec gives '${command}' to ${ids[0]}; modules.json does not`)
          }
        }
      }
    }

    // Form 2 — §3.6's module table: "**Owns `sub-reload`**" inside the row of
    // the module that owns it.
    const rowId = moduleIdsIn(cells[1] ?? '')[0]
    if (rowId) {
      for (const m of line.matchAll(/[Oo]wns\s+`([a-z][a-z0-9-]*)`/g)) {
        const command = m[1] as string
        if (!MPV_COMMANDS.has(command)) continue
        if (!owns(rowId, command)) {
          missing.push(`§3.6's ${rowId} row says it owns '${command}'; modules.json does not`)
        }
      }
    }
  }

  assert.deepEqual(
    [...new Set(missing)],
    [],
    `the spec claims command ownership the manifest does not encode. Prose that nothing ` +
      `enforces is how 'seek' ended up owned by nobody:\n  ${[...new Set(missing)].join('\n  ')}`
  )
})
